= Entwicklerdokumentation
:project_name: name-des-projekts
:toc: left
:numbered:

[options="header"]
[cols="1, 1, 3, 3"]
|===
|Version | Datum   | Autor | Beschreibung
|0.1	| 15.11 | Andrejs | Package Diagram + External Dependencies
|0.2	| 18.11 | Oleh | Start of package diagram for sales package
|0.3	| 18.11 | Andrejs | Vorgaben zum Betrieb der Software
|...	| ... | ... | ...
|===


== Einführung
* Aufgabenstellung

== Randbedingungen
* Hardware-Vorgaben

[cols="1, 1"]
|===
|Maus	| Benutzer 
|Tastatur	| Benutzer 
|Rechner mit Internetverbindung | Benutzer
|Server mit Linux	| Unternehmen
|===

* Software-Vorgaben

The following (or newer) Java version is necessary to run the application:

[cols="1"]
|===
|Java 21
|===

The following (or newer) browser versions are necessary to use the application:
[cols="1, 1"]
|===
|Firefox |130.0.0
|Google Chrome |131.0.0
|Chromium based browsers |130.0.0
|Opera |114.0.0
|Safari |18.0
|===

* Vorgaben zum Betrieb der Software
Das Program soll in dem Blumenladen intern (d.h. von den Mitarbeitern) bedient werden, um die Geschäftsprozesse (u.a. Verkauf, Einkauf, Bluemnpflegen-Dienstleistungen usw.) zu digitalisieren und vereinfachen. 

Das Backend soll auf einem Server mindestens in Arbeitszeiten (oder länger) laufen und mittels des Netzwerkes zugänglich für Enduser-Rechener sein.

Die Nutzer sind Frau Floris (Besitzerin) und ihre Nichte (Mitarbeiterin im Service). Es wird vorausgesetzt, dass sie den Rechner im Wesentlichen bedienen können.  

Das System soll keiner technischen Wartung bedürfen. Sämtliche Daten sollen persistent in einer Datenbank gespeichert und über die Anwendung zugänglich sein (z.B. sollten für Frau Floris keine SQL-Kenntnisse erforderlich sein).

== Kontextabgrenzung
* Kontextdiagramm

== Lösungsstrategie
=== Erfüllung der Qualitätsziele
[options="header"]
|=== 
|Qualitätsziel |Lösungsansatz
|... |...
|===

=== Softwarearchitektur
* Beschreibung der Architektur anhand der Top-Level-Architektur oder eines Client-Server-Diagramms

=== Entwurfsentscheidungen
* Verwendete Muster
* Persistenz
* Benutzeroberfläche
* Verwendung externer Frameworks

=== Use of external frameworks

NOTE: Name the used external frameworks, in which packages you used them, and why you used them in your application. You only need to describe the high level artifact.


[options="header"]
|===
|Exterenes Framework|Kategorie|Beschreibung
|Spring Boot |General purpose |…
|Spring Data JPA |Persistence |…
|Spring Security |Security |…
|Semantic UI |UI |…
|jQuery |UI |…
|salespointframework |Backend | Zur Entwicklung von Point-of-Sales-Anwendungen (PoS) mit Spring Framework und Spring Boot. Es besteht aus einer Vielzahl von Geschäftsmodulen, die es dem Nutzer ermöglichen, darauf aufbauend anspruchsvolle Webanwendungen zu implementieren.
|Bootstrap | UI | Stellt Seiten-Layout-Tools und vordefinierte HTML-Elemente zu Verfügung. 
|===

NOTE: If you use JavaScript frameworks like Bootstrap, HTMX, etc. you have to add them to the list. The category is
mostly _UI_ and/or _Communication_.


[options="header", cols="1,2,3"]
|===
|Externes Package |Verwendet von |Warum
|salespointframework |Backend | Zur Entwicklung von Point-of-Sales-Anwendungen (PoS) mit Spring Framework und Spring Boot. Ermöglicht, darauf aufbauend anspruchsvolle Webanwendungen zu implementieren.
|Bootstrap | Frontend | Stellt Seiten-Layout-Tools und vordefinierte HTML-Elemente zu Verfügung. 
|Thymeleaf | Frontend | ...
|===

== Bausteinsicht
* Package-Diagramm

[[package_diagram]]
image::./models/images/package_diagram_c.svg[package diagram]


* Entwurfsklassendiagramme der einzelnen Packages

=== Sales

[[top_level_diagram]]
image::./models/images/package-diagram-sales-a.svg[package diagram, 100%, 100%, pdfwidth=100%, title= "Package diagramm für sales packge in UML", align=center]

[options="header"]
|=== 
|Klasse/Enumeration |Description
|... |...
|===

=== Rückverfolgbarkeit zwischen Analyse- und Entwurfsmodell
_Die folgende Tabelle zeigt die Rückverfolgbarkeit zwischen Entwurfs- und Analysemodell._

[options="header"]
|===
|Klasse/Enumeration (Analysemodell) |Klasse/Enumeration (Entwurfsmodell)
|... |...
|===

== Laufzeitsicht
* Darstellung der Komponenteninteraktion anhand eines Sequenzdiagramms, welches die relevantesten Interaktionen darstellt.


