:project_name: Blumenladen
:toc: left
:numbered:
= Pflichtenheft __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2021          | Autor       | Initiale Version
|0.1.1     | In Arbeit   | 21.10.2024          | Andrejs       | Stakeholders (Akteure)
|0.2     | In Arbeit   | 28.10.2024          | Andrejs       | Init UseCase & Class Diagrammen
|0.2.1     | In Arbeit   | 28.10.2024          | Andrejs       | UseCase & Class Diagrammen
|0.2.2     | In Arbeit   | 31.10.2024          | Davyd       | Funktionale und nicht-funktionale Anforderungen
|0.3      | In Arbeit   | 31.10.2024      | Bechir    |  Bearbeitung in Klassendiagram und beschreiben die Klassen und Enum
|0.3.1     | In Arbeit    | 31.10.2024     | Bechir    | schreiben der Zussammenfassung
|===

== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze:|
Das System für Frau Rosa Floris' Blumenshop digitalisiert und vereinfacht verschiedene Geschäftsprozesse:|
	1. Finanzverwaltung: Das System hilft Frau Floris dabei, Rechnungen zu verwalten, Tegesrechnungen und Monatsrechnungen zu erstellen sowie den Verlust durch verwelkte Blumen zu kalkulieren.|
	2. Vertrieb und Verkauf: Der Vertrieb umfasst den Einkauf von Blumen als Rohstoff, den Verkauf von Blumen oder Boquets.|
	3. Lagermanagement: Frau Floris kann den Überblick über die verfügbare Ware behalten.|
	4. Serviceangebote: Das System unterstützt Dienstleistungen wie: das Dekorieren von Veranstltungen mit Blumen| regelmäßige Blumenlieferung| die Bereitstellung von Boquets und Blume zur Abholung im Lade. (wenn die Kunden spezielle Services und Angebote nutzen möchten).|
	5. Admin-Bereich: Der Administrator verwaltet Benutzerberechtigungen und simuliert den Großhändler-Katalog.|
Die Kunden könnten mit Karte oder Bar bezahlen.|
Die Rechnungen lassen sich nach dem Einkauf bezahlt.|

== Aufgabenstellung und Zielsetzung
Zuallererst braucht die Software eine Übersicht von dem Angebot des Großhändlers. Dabei
soll es möglich sein, Bestellungen aufzunehmen und sofort losschicken. Sobald
der Großhändler die Bestellung bestätigt hat, können die Angaben in den aktuellen
Bestand übernommen werden, da die Lieferung umgehend erfolgt. Zu
jeder Blumensorte stehen im Computer die aktuelle Anzahl sowie der Ein- und
Verkaufspreis. Außerdem wird die Rechnung des Großhändlers erfasst und der
Betrag sofort als Ausgabe für die tägliche Abrechnung verbucht.
Wenn ein Kunde in den Laden kommt und sich seinen Blumenstrauß ausgesucht
hat, muss in einem Rechnungsformular die Anzahl der dafür verwendeten
Pflanzen eintragen werden. Die Software berechnet den Verkaufspreis und der
Kunde kann entscheiden, ob er den Blumenstrauß in dieser Zusammenstellung
wirklich kaufen möchte. Wenn sich der Kunde entschieden hat, bekommt er
seine Rechnung, der Blumenbestand wird aktualisiert und der Betrag in der
Kasse wird angeglichen.

Ähnlich funktioniert es auch bei den Fertigsträußen, die Frau Floris herstellt,
wenn gerade keine Kunden im Laden sind. Abends stellt die Software die Einnahmen
und Ausgaben automatisch zusammen und gibt den aktuellen Kassenstand
aus.

Auch das Problem mit der Organisation für Hochzeiten soll die neue Software
lösen. Bereits während des Beratungsgespräches werden alle Angaben
eingegeben. Die endgültige Bestellung wird ausgelöst, wenn man sich über alle
Details einig geworden ist. Die benötigten Blumen erscheinen einen Tag vor
dem großen Ereignis automatisch in der Bestellung beim Großhändler und eine
Rechnung für Frau Meier wird erzeugt. Frau Floris kann diese als “bezahlt”
markieren, sobald das Geld (bar oder auf dem Konto) eingetroffen ist und somit
die Abrechnungen aktualisieren.

Der gemeinsam mit der Nichte geplante Pflanzenservice soll auch von der Software
unterstützt werden. Eine Firma, die eine Ausstattung ihrer Büro- und
Sitzungsräume mit Grünpflanzen wünscht, erteilt Frau Floris einen entsprechenden
Auftrag. Sie bestellt die benötigten Pflanzen beim Großhändler und arrangiert
sie in den Räumlichkeiten der Firma. Zusätzlich kann ein Servicevertrag
abgeschlossen werden, der die wöchentliche Pflege der Pflanzen durch Frau Floris
und auf Wunsch und zu anderen Konditionen auch die Versorgung mit frischen
Schnittblumen umfasst.

Nur die verwelkten Blumen in ihrem Laden kann die neue Software nicht aussortieren.
Diese müsste Frau Floris abends aber als Verlust in die Abrechnung
aufnehmen können.

*Also, am Ende soll ein internes Website fertig sein, das alle Geschäftsprozesse in dem Blumenladen von Frau Floris digitalisiert und in einigen Fällen auch automatisiert. Das wird zur einer starken Optimisierung von allen Bereichen der Geschäftsführung.*

== Produktnutzung
Das System soll einer Frau Floris als Assistentin bei der Betreuung ihres Blumenladens dienen (z.B. Blumen und Sträuße an Kunden verkaufen, bei Großhaendler einkaufen, und andere Dienstleistungen anbieten). Die Software soll auf einem lokalen Server laufen und über den Webbrowser auf einem lokalen Rechner verfügbar sein.

Die primären Nutzer der Software sind Frau Floris und ihre Nichte, die nicht unbedingt einen technischen Hintergrund haben.

Das System soll keine technische Wartung benötigen. Alle Daten sollen dauerhaft in einer lokalen Datenbank gespeichert werden und über die Anwendung zugänglich sein (z.B. sollten für Frau Floris keine SQL-Kenntnisse erforderlich sein). Die Geldoperationen sollten auch mit Hilfe eines lokalen Geldmanagers durchgeführt werden können.

== Interessensgruppen (Stakeholders)
Welche realen und juristischen Personen(-gruppen) haben Einfluss auf die Anforderungen im Projekt?

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|Frau Rosa Floris  | Besitzerin - Verwaltung Finanzen und Lager. Berät Kunden bei Hochzeits- und Eventbestellungen.
|Rosas Nichte  | Leiterin Pflanzenservice - Bestellung für den Auftrag benötigten Pflanzen und Arrangierung der Räumlichkeiten vor Ort
|Kunden  | Kaufen Einzelblumen oder Blumensträuße. Einige Kunden bestellen spezielle Aufträge für Hochzeiten oder andere Veranstaltungen und erhalten Beratung.
|Großhändler  | Verkaufen Blumen an das Unternehmen 
|Administratoren | Verwalten das System, erteilen die Berechtigungen für Nutzer und sorgen für die reibungslose Funktion der Software.

|===

=== Überblick Anwendungsfalldiagramm

[[use_case_diagram]]
image::./models/images/use_cases_b.svg[use case diagram, 100%, 100%, pdfwidth=100%, title= "Anwendungsfalldiagramm für {project_name} in UML", align=center]

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Funktionale Anforderungen

Dieser Abschnitt gibt einen Überblick über die funktionalen Anforderungen des Systems.

Die Tabellen enthalten:

 - Eine eindeutige Kennung der Anforderung (ID), die für die Referenzierung während des gesamten Projekts verwendet werden kann
 - Die aktuelle Version der Anforderung, da Änderungen an einer Anforderung während des Projekts auftreten können
 - einen Kurznamen für die Anforderung
 - Die Beschreibung der Anforderung

Die Anforderungen werden in Muss-Kriterien und Kann-Kriterien unterteilt:

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

[options="header", cols="2h,1,3,12"]
|===

| ID | Version | Name | Beschreibung

| [[F0001]]<<F0001>>
| v0.1
| Rechnungen verwalten
| Das System soll die Verwaltung von Rechnungen für jede Transaktion ermöglichen. Es speichert die Details jeder für Kundenkäufe oder Großbestellungen erstellten Rechnung, damit Frau Floris die Finanzunterlagen im Überblick behalten kann.

| [[F0002]]<<F0002>>
| v0.1
| Tagesabrechnung
| Das System soll am Ende des Tages die Einnahmen und Ausgaben automatisch zusammenstellen und den aktuellen Kassenstand anzeigen.

| [[F0003]]<<F0003>>
| v0.1
| Monatsabrechnung
| Das System soll eine monatliche Abrechnung der Einnahmen und Ausgaben erstellen, um einen detaillierten Überblick über die finanzielle Lage des Geschäfts zu bieten.

| [[F0004]]<<F0004>>
| v0.1
| Verwelkte Blumen als Verlust
| Das System soll es ermöglichen, abends verwelkte Blumen als Verlust in die Abrechnung aufzunehmen.

| [[F0101]]<<F0101>>
| v0.1
| Blumen als Rohstoff verwalten
| Das System soll den aktuellen Blumenbestand sowie Ein- und Verkaufspreise der Blumen anzeigen, basierend auf den Bestellungen beim Großhändler und dem Verkauf im Laden.

| [[F0102]]<<F0102>>
| v0.1
| Lagerbestand verwalten
| Das System soll die Verwaltung des Lagerbestands unterstützen und Bestellungen basierend auf aktuellen Bedürfnissen und zukünftigen Veranstaltungen ermöglichen.

| [[F0103]]<<F0103>>
| v0.1
| Verkauf von Blumen im Laden
| Das System soll den Verkauf von Blumen im Laden erleichtern, indem es die Anzahl der verkauften Blumen erfasst, den Verkaufspreis berechnet und den Lagerbestand aktualisiert.

| [[F0104]]<<F0104>>
| v0.1
| Fertigsträuße erstellen
| Das System soll es ermöglichen, dass Frau Floris Fertigsträuße erstellt und deren Bestand im System verwaltet.

| [[F0201]]<<F0201>>
| v0.1
| Veranstaltung mit Blumen ausstatten
| Das System soll eine vollständige Verwaltung für die Organisation von Veranstaltungen mit Blumenschmuck bieten, einschließlich Beratung, Bestellung und Rechnungserstellung.

| [[F0202]]<<F0202>>
| v0.1
| Blumenservice für Firmen anbieten
| Das System soll die Möglichkeit bieten, für Firmen einen Pflanzenservice zu organisieren, einschließlich der Bestellung und Lieferung von Pflanzen sowie eines optionalen Pflegevertrags.

|===

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

[options="header", cols="2h,1,3,12"]
|===

| ID | Version | Name | Beschreibung

| [[F0203]]<<F0203>>
| v0.1
| Blumen zur Abholung im Laden
| Das System soll es Kunden ermöglichen, Blumen im Voraus zu bestellen und zur Abholung im Laden bereitzustellen.

| [[F0901]]<<F0901>>
| v0.1
| Berechtigungen zuweisen
| Das System soll die Möglichkeit bieten, Berechtigungen für verschiedene Benutzerrollen zu verwalten, um die Sicherheit und die Struktur der Zugriffsrechte im System zu gewährleisten.

|===

== Nicht-Funktionale Anforderungen

Dieser Abschnitt gibt einen Überblick über die nicht-funktionalen Anforderungen des Projekts Blumenladen.
Diese Anforderungen beschreiben, wie das System funktionieren soll und in welchen Grenzen es arbeiten soll.

=== Qualitätsziele

Die folgende Tabelle zeigt die Qualitätsanforderungen, die in welchem Umfang erfüllt werden müssen.
Die erste Spalte listet die Qualitätsanforderungen auf, während in den folgenden Spalten die Priorität mit einem "x" markiert ist.
Die zugewiesene Priorität muss bei der Formulierung der konkreten nicht-funktionalen Anforderungen berücksichtigt werden.

1 = Weniger wichtig ..
5 = Sehr wichtig
[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Qualitätsanforderung       | 1 | 2 | 3 | 4 | 5
|Verfügbarkeit               |   |   |   | x |
|Leistungsfähigkeit          |   |   | x |   |
|Benutzerfreundlichkeit      |   |   |   | x |
|Sicherheit                  |   |   |   |   | x
|Wartbarkeit                 |   |   | x |   |
|===

=== Konkrete Nicht-Funktionale Anforderungen

:desired-uptime: 99,5%

[options="header", cols="2h, 1, 3, 12"]
|===
|ID
|Version
|Name
|Beschreibung

|[[NF0010]]<<NF0010>>
|v0.1
|Verfügbarkeit - Betriebszeit
a|
Das System soll eine Betriebszeit von mindestens **{desired-uptime}** erreichen, um sicherzustellen, dass die Anwendung für Benutzer zuverlässig verfügbar ist.

|[[NF0020]]<<NF0020>>
|v0.1
|Sicherheit - Passwortspeicherung
a|
Passwörter der Benutzer sollen nur als Hash-Werte gespeichert werden, um Diebstahl und Missbrauch zu verhindern.

|[[NF0030]]<<NF0030>>
|v0.1
|Leistungsfähigkeit - Reaktionszeit der Benutzeroberfläche
a|
Die Reaktionszeit der Benutzeroberfläche soll nicht mehr als 2 Sekunden für jede Hauptfunktionalität betragen, wie das Abrufen des Lagerbestands, das Erstellen von Rechnungen und das Verwalten von Bestellungen.

|[[NF0040]]<<NF0040>>
|v0.1
|Benutzerfreundlichkeit - Intuitive Bedienung
a|
Die Benutzeroberfläche des Systems soll so gestaltet sein, dass Mitarbeiter ohne technische Vorkenntnisse in der Lage sind, die wichtigsten Funktionen wie Rechnungsstellung, Bestandsverwaltung und Bestellungserstellung innerhalb von maximal 1 Stunde Einarbeitungszeit zu beherrschen.

|[[NF0050]]<<NF0050>>
|v0.1
|Wartbarkeit - Dokumentation und Code-Kommentare
a|
Der Quellcode des Systems soll ausführlich dokumentiert sein, um spätere Wartung und Erweiterungen zu erleichtern. Jede wichtige Funktion soll mindestens einen erklärenden Kommentar enthalten, und es soll eine klare Struktur für zukünftige Entwickler vorgegeben sein.

|===

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

[[analysis_class_diagram]]
image::./models/images/analysis_class_c.svg[Analysenklassendiagramm, 100%, 100%, pdfwidth=100%, title= "Analysenklassendiagramm für {project_name} in UML", align=center]

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|1. Client|Enthält Informationen über den Kunden, wie Name, Adresse und Telefonnummer. |
|2. ServiceContract |Erbt von der Klasse Ordner und enthält ein Client-Objekt sowie ein Datum-Attribut. Das Attribut frequence beschreibt, wie oft eine Lieferung erfolgen soll. |
|3. PaymentMethod  |Enthält zwei Attribute – Card, damit der Kunde mit Karte zahlen kann, und Cash, damit der Kunde bar bezahlen kann. |
|4.Invoice |Jedes Invoice-Objekt hat eine einzigartige ID und eine PaymentMethod.|
|5.Product  |Jedes Product hat einen Namen, Einkaufspreis, Verkaufspreis und eine einzigartige ID. |
|6.Flower | Erbt von Product und hat ein zusätzliches Attribut für die Farbe. |
|7.Bouquet |Erbt von Product und besitzt ein Attribut additionalPrice. Jedes Bouquet kann aus zwei oder mehr Blumen bestehen. |
|8.Storage |Ein Storage enthält mehrere Produkte. |
|9.CashRegister |Ein CashRegister kann mehrere FinancialReport-Objekte enthalten. |
|10.FinancialReport |Jedes FinancialReport-Objekt enthält Informationen über die Finanzen, wie Einnahmen und Ausgaben, den aktuellen Stand (Balance) und eine Zahl für den Profit. Die Daten werden aus dem CashRegister genutzt. |
|11.DailyFinancialReport |Erbt von FinancialReport und behandelt täglich die Attribute. |
|12.MonthlyFinancialReport |Erbt von FinancialReport und verarbeitet die Attribute monatlich. |
|13.OrderStatus  |Eine Enumeration, die nur zwei Werte enthält: PAID und NOT_PAID. |
|14.Order  |Eine Bestellung kann ein oder mehrere Produkte, eine ID, eine Variable vom Typ OrderStatus und eine Invoice enthalten. |
|15.FlowerShop |Verfügt über ein Management für das Storage, bietet eine Übersicht über alle Bestellungen, hat eine unbegrenzte Anzahl an RegisteredUsers und ein CashRegister. |
|16.RegisteredUser|Repräsentiert Benutzer, die bereits registriert sind.  |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch
erfüllt.
Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden.
D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (, welches ein
Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== Glossar
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?
- Laden - Blumenladen von Frau Floris, für dem wird die System entwickelt.
- Administrator - eine Person, die den Auftraggeber über den Website nach dem Einsetzung beraten wird. Administrator kann den Website verwalten.
- Produkt - Waren, die in dem Laden verkauft werden. Nun - Schnittblumen und Blumensträusen.
- Kunde - Die Person, die Produkte in dem Laden kauft bzw. die Services, wie z.B Dekorieren und Lieferung der Blumen von dem Laden bestellt.
- Auftraggeber - der Laden
- Nutzer des Systems - Frau Floris, ihre Nichte, andere Mitarbeiter von dem Laden (in dem Fall, wenn es die geben wird).
- Lager - Die Menge von Blumen, die für die sofortige Verkauf in dem Laden bereit sind. Auf English - Stock.
- Großhändler - ein Unternehmen, wo der Laden alle Blumen für den Lager in großen Mengen und billiger als Verkaufspreis bestellt.
- Service - Vorherig vereinbarte reguläre oder einmalige Leistung des Ladens für ein:e Kund:in. Eine Vorbereitung in Form von einer Bestellung von exakt allen benötigten Blumen von dem Großhändler ist in Fällen von einer großen Bestellung (wie eine Hochzeit) notwendig.
- Rechnungsformular - eine Sektion von dem Website, wo Nuzter des Systems mit dem geeignetem Zugengsstatus die von Kunden gewählte Produkte einfügen, damit die nach der Bezahlung weiterbearbeitet sein werden, und Kassenstand mit dem Lager aktualisiert, und die Rechnung - erstellt werden können.
== Offene Punkte
