= Zeiterfassung für Gruppe 7

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Andrejs |Davyd |Vadym |Oleh |Bechir |Valeriia |Paul |Dev8 |Meeting
|1    |200   |30    |150    |80    |180    |160    |170|…    |45   
|2  |500   |450    |480    |460    |450    |440    |380|…    |60    
|3  |490   |…    |…    |…    |410    |…    |…    |…    |40    
|4  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|5  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|6  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|7  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|8  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|9  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|10  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|11  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|12  |…   |…    |…    |…    |…    |…    |…    |…    |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
