= Zeiterfassung für Gruppe 7

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Andrejs |Davyd |Vadym |Oleh |Bechir |Valeriia |Paul |Meeting
|1    |200   |30    |150    |80    |180    |160    |170    |45
|2  |500   |450    |480    |460    |450    |440    |380    |60
|3  |490   |320    |350    |410    |470    |340    |400        |40
|4  |400   |300    |300    |280    |380    |300    |150    |40
|5  |340   |1500    |1800    |250    |450    |1400   |750   |40
|6  |2520   |1000    |1080    |450    |1100   |1000    |120    |45
|7  |220   |500    |20    |110    |150    |400    |90   |100
|8  |200   |450    |600    |500    |200    |300    |700    |65
|9  |500   |1500    |1200    |1050    |500    |650   |480   |50
|10  |720   |700    |1500    |850    |620    |900    |360    |60
|11  |300   |400    |200    |250    |200    |350    |180   |…
|12  |…   |…    |…    |…    |…    |…    |…    |…
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
